import { StyleSheet } from "react-native";
import { colors } from "@/styles/variable";
const shoppingCalenderStyle = StyleSheet.create({
  container: {
    width: "100%",
    padding: 12,
    gap: 10,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    backgroundColor: colors.white,
    borderRadius: 8,
  },
  containerCalenderToday: {
    width: "100%",
    display: "flex",
    justifyContent: "flex-start",
  },
  containerCalender: {
    width: "100%",
    // justifyContent: "space-between",
    paddingVertical: 12,
    display: "flex",
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#B7B7B7",
  },
  containerItemCalender: {
    marginRight: 10,
    width: 40,
    height: 40,
    borderRadius: 20,
    flexDirection: "column",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.white90,
  },
  textItemCalender: {
    // fontFamily: "Inter",
    fontWeight: "regular",
    fontSize: 14,
    color: colors.black80,
  },
  containerNoSchedule: {
    width: "100%",
    padding: 10,
    gap: 10,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    backgroundColor: "#E6EDF5",
    borderRadius: 4,
  },
  textNoSchedule: {
    // fontFamily: "Inter",
    fontWeight: "regular",
    fontSize: 11,
    color: colors.black60,
  },
  createButton: {
    height: 32,
    paddingHorizontal: 24,
    backgroundColor: colors.success, // Hoặc màu nào bạn muốn
    borderRadius: 4,
    alignItems: "center",
    justifyContent: "center",
  },
  textCreateButton: {
    // fontFamily: "Inter",
    color: colors.white,
    fontWeight: "regular",
    fontSize: 16,
  },
  dotSpecial: {
    width: 4,
    height: 4,
    backgroundColor: colors.primary,
    borderRadius: 50,
  },
  containerBoxData: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  containerEditData: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 10,
  },
  containerImg: {
    width: 24,
    height: 24,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.white90,
    borderRadius: 4,
  },
  containerDataToday: {
    width: "100%",
    display: "flex",
    padding: 10,
    flexDirection: "column",
    gap: 10,
    borderRadius: 4,
    backgroundColor: "#E6EDF5",
  },
  containerItemDataToday: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 2,
    gap: 12,
    backgroundColor: colors.white60,
    padding: 8,
  },
  containerWeight: {
    width: 56,
    height: 56,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.white,
    borderRadius: 50,
  },
  textWeight: {
    // fontFamily: "Inter",
    fontWeight: "regular",
    fontSize: 16,
    color: colors.textsecondary,
  },
  containerDetailProduct: {
    display: "flex",
    flexDirection: "row",
    gap: 8,
    width: "70%",
  },
  containerTextDetailProduct: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  textTitleProduct: {
    // fontFamily: "Inter",
    fontWeight: "regular",
    fontSize: 14,
    color: colors.black,
  },
  containerTypeTree: {
    display: "flex",
    flexDirection: "row",
    gap: 4,
    width: "100%",
  },
  textTypeTree: {
    fontWeight: "regular",
    fontSize: 11,
    color: colors.black60,
  },
  containerAddress: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    width: "100%",
  },
  containerAddress1: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    gap: 4,
    alignItems: "center",
  },
  containerAddressDot: {
    width: 4,
    height: 4,
    borderRadius: 50,
    backgroundColor: colors.bluebg,
  },
  containertextAddress1: {
    width: "100%",
  },
  textAddress1: {
    flexWrap: "wrap",
    fontSize: 11,
    color: colors.black60,
  },
  containerSelectedItemDataToday: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 2,
    gap: 12,
    backgroundColor: colors.success,
    padding: 8,
  },
  containerButtonSuccess: {
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  ButtonSuccess: {
    height: 32,
    paddingHorizontal: 24,
    backgroundColor: colors.bluebg,
    borderRadius: 4,
    alignItems: "center",
    justifyContent: "center",
  },
  textButtonSuccess: {
    fontSize: 16,
    fontWeight: "regular",
    color: colors.white,
  },
});
export default shoppingCalenderStyle;
