import { StyleSheet } from "react-native";
import { colors } from "@/styles/variable";
const shoppingScheduleStyle = StyleSheet.create({
  container: {
    width: "100%",
    gap: 16,
    display: "flex",
    flexDirection: "column",
    paddingBottom: 100,
  },
  containerCalenderEdit: {
    padding: 10,
    backgroundColor: colors.white,
    borderRadius: 8,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  calender: {
    display: "flex",
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
  },
  iconCalender: {
    width: 20,
    height: 20,
  },
  editCalender: {
    borderRadius: 4,
    width: 24,
    height: 24,
    backgroundColor: colors.white90,
    justifyContent: "center",
    alignItems: "center",
    display: "flex",
  },
  calendarContainer: {
    position: "absolute",
    width: "100%",
    top: 60,
    overflow: "hidden",
    zIndex: 2,
  },
  containerSearch: {
    marginTop: 16,
    width: "100%",
    padding: 10,
    gap: 16,
    display: "flex",
    flexDirection: "column",
    backgroundColor: colors.white,
    borderRadius: 8,
  },
  containerInputSearch: {
    width: "100%",
    borderRadius: 4,
    display: "flex",
    flexDirection: "column",
    borderRadius: 4,
    alignItems: "center",
    gap: 4,
  },
  containerInput: {
    width: "100%",
    borderRadius: 4,
    display: "flex",
    flexDirection: "row",
    borderWidth: 1,
    borderColor: colors.white60,
    borderRadius: 4,
    alignItems: "center",
  },
  input: {
    height: 40,
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderRadius: 4,
    width: "88%",
  },
  containerImgSearch: {
    width: 32,
    height: 40,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  iconSearch: {
    width: 26,
    height: 26,
    marginRight: 4,
  },
  lineHeight: {
    width: 1,
    height: 28,
    backgroundColor: colors.white60,
    marginHorizontal: 4,
  },
  containerFoodCate: {
    width: "100%",
    paddingBottom: 10,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  textFoodCate: {
    // fontFamily: "Inter",
    fontSize: 12,
    fontWeight: "medium",
    color: colors.black80,
  },
  textShowFood: {
    // fontFamily: "Inter",
    fontSize: 12,
    fontWeight: "medium",
    color: colors.primary,
  },
  suggestionBox: {
    width: "100%",
    borderRadius: 4,
    borderBottomWidth: 1,
    borderBottomColor: colors.white60,
    display: "flex",
    flexDirection: "column",
    borderWidth: 1,
    borderColor: colors.white60,
  },
  suggestionItem: {
    paddingVertical: 6,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    paddingHorizontal: 10,
    justifyContent: "space-between",
    alignItems: "center",
  },
  suggestionItem_box: {
    width: "100%",
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: colors.white60,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  iconNoItemFood: {
    width: 32,
    height: 32,
  },
  imageCategories: {
    width: 72,
    height: 72,
    overflow: "hidden",
    resizeMode: "cover",
  },
  containerImgNameFood: {
    display: "flex",
    flexDirection: "row",
    gap: 6,
  },
  containerDetailFood: {
    gap: 4,
    display: "flex",
    flexDirection: "column",
  },
  containerButtonSuccess: {
    marginTop: 20,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  ButtonSuccess: {
    height: 32,
    paddingHorizontal: 24,
    backgroundColor: colors.bluebg,
    borderRadius: 4,
    alignItems: "center",
    justifyContent: "center",
  },
  textButtonSuccess: {
    fontSize: 16,
    fontWeight: "regular",
    color: colors.white,
  },
  textNameFood: {
    fontFamily: "Roboto",
    fontSize: 16,
    fontWeight: "regular",
    color: colors.black100,
  },
  textTypeFood: {
    fontFamily: "Roboto",
    fontSize: 10,
    fontWeight: "regular",
    color: colors.black60,
  },
  textaddFood: {
    fontFamily: "Roboto",
    fontSize: 12,
    fontWeight: "regular",
    color: colors.bluebg,
    marginRight: 4,
  },
  boxListFood: {
    marginTop: 10,
    display: "flex",
    flexDirection: "row",
    gap: 8,
  },
  boxItemFood: {
    paddingTop: 7,
    width: 86,
    borderRadius: 4,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.white80,
    marginRight: 8,
  },
  containerImgFood: {
    width: 72,
    height: 72,
    overflow: "hidden",
  },
  containerTextFood: {
    width: "100%",
    padding: 8,
  },
  textFood: {
    fontFamily: "Roboto",
    fontSize: 12,
    fontWeight: "regular",
    color: colors.black100,
  },
  containerCateShopping: {
    marginTop: 16,
    width: "100%",
    padding: 10,
    gap: 10,
    display: "flex",
    flexDirection: "column",
    backgroundColor: colors.white,
    borderRadius: 8,
  },
  textShoppingCate: {
    // fontFamily: "Inter",
    fontSize: 12,
    fontWeight: "medium",
    color: colors.black80,
  },
  containerListCateShopping: {
    zIndex: 0,
    // height: ,
    width: "100%",
    paddingVertical: 10,
    display: "flex",
    flexDirection: "column",
    borderRadius: 4,
    backgroundColor: colors.secondary,
    paddingHorizontal: 10,
  },
  containerItemCateShopping: {
    width: "100%",
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: colors.white60,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    position: "relative",
  },
  containerInputCateShopping: {
    gap: 4,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 2,
    borderWidth: 1,
    borderColor: colors.white60,
    height: 60,
    width: 120,
  },
  inputShopping: {
    fontFamily: "Roboto",
    fontSize: 12,
    fontWeight: "regular",

    paddingLeft: 6,
    width: "50%",
    whiteSpace: "nowrap",
  },
  countFood: {
    minWidth: 50,
    maxWidth: 50,
    display: "flex",
    flexDirection: "row",
    gap: 5,
    paddingRight: 6,
    alignItems: "center",
  },
  countUnit: {
    position: "relative",
    display: "flex",
    flexDirection: "row",
    width: "100%",
    justifyContent: "space-between",
    alignItems: "center",
    paddingRight: 15,
  },
  unitBox: {
    backgroundColor: "white",
    position: "absolute",
    top: 30,
    left: -10,
    zIndex: 1000, // Tăng zIndex để đảm bảo luôn nằm trên các thành phần khác
    borderWidth: 1,
    borderColor: "gray",
    borderRadius: 5,
    width: 70, // Điều chỉnh chiều rộng nếu cần
    elevation: 5, // Dành cho Android để nâng box lên
    shadowColor: "#000", // Dành cho iOS để tạo đổ bóng
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },

  unitItem: {
    padding: 10,
  },
  unitText: {
    zIndex: 0,
    textAlign: "center",
    fontSize: 12,
    fontWeight: "regular",
    color: colors.white60,
  },
});
export default shoppingScheduleStyle;
